### ISSUE TITLE
Repeat installing Firmware after PA Issue

### ISSUE THREAD

**Issue by askthewood** [o5edaxi/paloversion#2]
We get the issue "The software manager is currently in use. Please try again later." from our Palo Alto after upgrading from 10.1.4 to 10.2.0.
Is it possible to repeat the firmware uploading/installing process as long as another issue occur? Currently the script will fail if this issue occur, but the second time is successful.
https://knowledgebase.paloaltonetworks.com/KCSArticleDetail?id=kA14u0000004MA7CAM

**Comment by o5edaxi** [comment]
Hi,

yes, this would be no problem, but we have to know at which point the error happens. Can you reproduce this issue? What model is it and does it break during upload, or install?

**Comment by askthewood** [comment]
Hi, 
I´m using PA 410 and seems it breaks after uploading, when the script wants to install the Firmware.
Attached all Logs and Files i´ve used.
One Log called "LogPA410.txt" is the log output directly from PA 410.
[400.csv](https://github.com/o5edaxi/paloversion/files/13660206/400.csv)
[023101032058.log](https://github.com/o5edaxi/paloversion/files/13660207/023101032058.log)
[content.csv](https://github.com/o5edaxi/paloversion/files/13660208/content.csv)
[LogPA410.txt](https://github.com/o5edaxi/paloversion/files/13660210/LogPA410.txt)
[PaloVersionBatch.log](https://github.com/o5edaxi/paloversion/files/13660211/PaloVersionBatch.log)

EDIT: After 10 Minutes i started the script again and it was successfull

**Comment by o5edaxi** [comment]
Hi,

thanks for the logs, I will try to recreate and fix that. I have already had to add workarounds for 410's as you can tell from the "Resource temporarily unavailable" part, seems they have a hard time with the larger files.

For the moment you can just rerun the script automatically if it fails using the "||" in bash:

paloversion.sh -z "192.0.2.1" "admin" "password" "/home/PA/Firmware/" "10.2.7" || paloversion.sh -z "192.0.2.1" "admin" "password" "/home/PA/Firmware/" "10.2.7"

should also work with batch mode:

paloversion.sh -f -z "192.0.2.1" "admin" "password" "/home/PA/Firmware/" "10.2.7" "eth0" || paloversion.sh -z "192.0.2.1" "admin" "password" "/home/PA/Firmware/" "10.2.7" "eth0"

**Comment by o5edaxi** [comment]
Hi,

I couldn't reproduce the issue on the same model and version, but I tried to fix it anyway. Let me know if it works with the latest code.

**Comment by askthewood** [comment]
Hi, 
Unfortunately it´s not working, i tried it twice and every time the same issue. 
Script will recognize that SWM (SoftwareManager) in´t available and will wait 1 Min:
```
14:41:21 Installing software version 10.2.0 on device [fe80::8e36:7aff:fe03:be8]. Job ID is 3.
14:41:30 Firewall [fe80::8e36:7aff:fe03:be8] software installation is 0 percent complete.
14:41:36 Installation failed, software manager currently in use. Waiting 1 minute and trying again...
```

Directly on PA410 i can see following log entry:
```
admin@PA-410> show jobs id 3

Enqueued              Dequeued           ID                              Type                         Status Res                                                          ult Completed
----------------------------------------------------------------------------------------------------------------                                                          --------------
2023/12/29 05:39:00   05:39:00            3                         SWInstall                            FIN   F                                                         AIL 05:39:11
Warnings:

Details:Failed to install 10.2.0 with the following errors.
SW version is 10.2.0
The software manager is currently in use. Please try again later.
Failed to install   version  10.2.0  type  panos
```

After one minute, another try:

```
14:42:41 Installing software version 10.2.0 on device [fe80::8e36:7aff:fe03:be8]. Job ID is 4.
14:42:41 Installation failed, software manager currently in use. Waiting 1 minute and trying again...
14:43:52 Firewall return status unsuccessful

```
But on PA410:

```

admin@PA-410> show jobs id 4

Enqueued              Dequeued           ID                              Type                         Status Res                                                          ult Completed
----------------------------------------------------------------------------------------------------------------                                                          --------------
2023/12/29 05:40:20   05:40:20            4                         SWInstall                            ACT   P                                                          END        77%
Warnings:

Details:


admin@PA-410>
admin@PA-410>
admin@PA-410>
admin@PA-410>
admin@PA-410> show jobs id 4

Enqueued              Dequeued           ID                              Type                         Status Result Completed
------------------------------------------------------------------------------------------------------------------------------
2023/12/29 05:40:20   05:40:20            4                         SWInstall                            ACT   PEND        77%
Warnings:

Details:

admin@PA-410> show jobs all

Enqueued              Dequeued           ID  PositionInQ                              Type                         Status Result Completed
------------------------------------------------------------------------------------------------------------------------------------------
2023/12/29 05:40:20   05:40:20            4                                      SWInstall                            ACT   PEND        78%
2023/12/29 05:39:00   05:39:00            3                                      SWInstall                            FIN   FAIL 05:39:11
2023/12/29 05:28:11   05:28:11            2                       Device-certificate-fetch                            FIN   FAIL 05:34:17
2023/12/29 05:26:25   05:26:25            1                                        AutoCom                            FIN     OK 05:28:14
```
[023101032058.log](https://github.com/o5edaxi/paloversion/files/13795456/023101032058.log)

**Comment by o5edaxi** [comment]
I think I found the issue, please try again with the latest code.

**Comment by askthewood** [comment]
Is working now :+1:
